version: "3.9"

services:
  api:
    container_name: capstone_m4
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - IS_COMPOSE=true
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14.4-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=grupo05
      - POSTGRES_PASSWORD=grupo05dofelipe
      - POSTGRES_DB=capstone_m4
